Repository centrifuge/sdk, pull requests merged in 2025-09, with the labels that each got.

#195 fix: Investing with smart contract wallet
  package.json
  src/entities/Vault.ts
Labels: alpha

#200 fix: Retry message
  package.json
  src/Centrifuge.ts
Labels: alpha

#199 fix: transactions
  src/entities/OnOffRampManager.test.ts
  src/entities/OnOffRampManager.ts
Labels: no-release

#198 feat: retrieve members of a share class
  package.json
  src/entities/Investor.test.ts
  src/entities/Investor.ts
  src/entities/ShareClass.test.ts
  src/entities/ShareClass.ts
  src/utils/BigInt.ts
Labels: alpha

#233 feat: ability to disable relayers
  package.json
  src/entities/OnOffRampManager.test.ts
  src/entities/OnOffRampManager.ts
  src/entities/PoolNetwork.test.ts
Labels: minor
